import { db, toolsTable, siteSettingsTable, blogsTable, articlesTable } from "./index";

const tools = [
  // PDF Category
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into a single document in your desired order.",
    category: "pdf",
    icon: "FileText",
    route: "/tools/merge-pdf",
    isFeatured: true,
    isHidden: false,
    sortOrder: 1,
    inputFormats: [".pdf"],
    outputFormats: [".pdf"],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    description: "Extract specific page ranges or split a PDF into separate single pages.",
    category: "pdf",
    icon: "FileText",
    route: "/tools/split-pdf",
    isFeatured: true,
    isHidden: false,
    sortOrder: 2,
    inputFormats: [".pdf"],
    outputFormats: [".pdf"],
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce the file size of your PDF document without losing document quality.",
    category: "pdf",
    icon: "FileText",
    route: "/tools/compress-pdf",
    isFeatured: false,
    isHidden: false,
    sortOrder: 3,
    inputFormats: [".pdf"],
    outputFormats: [".pdf"],
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert PDF pages into high-quality JPEG images, downloaded as a ZIP.",
    category: "pdf",
    icon: "FileText",
    route: "/tools/pdf-to-jpg",
    isFeatured: false,
    isHidden: false,
    sortOrder: 4,
    inputFormats: [".pdf"],
    outputFormats: [".zip"],
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Convert JPG, PNG, or WebP images into a PDF document.",
    category: "pdf",
    icon: "FileText",
    route: "/tools/jpg-to-pdf",
    isFeatured: false,
    isHidden: false,
    sortOrder: 5,
    inputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputFormats: [".pdf"],
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    description: "Rotate pages of a PDF document by 90, 180, or 270 degrees.",
    category: "pdf",
    icon: "FileText",
    route: "/tools/rotate-pdf",
    isFeatured: false,
    isHidden: false,
    sortOrder: 6,
    inputFormats: [".pdf"],
    outputFormats: [".pdf"],
  },
  {
    slug: "watermark-pdf",
    name: "Watermark PDF",
    description: "Add custom text watermarks to your PDF pages.",
    category: "pdf",
    icon: "FileText",
    route: "/tools/watermark-pdf",
    isFeatured: false,
    isHidden: false,
    sortOrder: 7,
    inputFormats: [".pdf"],
    outputFormats: [".pdf"],
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract all text content from a PDF file easily.",
    category: "pdf",
    icon: "FileText",
    route: "/tools/pdf-to-text",
    isFeatured: false,
    isHidden: false,
    sortOrder: 8,
    inputFormats: [".pdf"],
    outputFormats: [".txt"],
  },
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    description: "Encrypt your PDF document with a secure password.",
    category: "pdf",
    icon: "FileText",
    route: "/tools/protect-pdf",
    isFeatured: false,
    isHidden: false,
    sortOrder: 9,
    inputFormats: [".pdf"],
    outputFormats: [".pdf"],
  },
  {
    slug: "remove-pdf-pages",
    name: "Remove PDF Pages",
    description: "Delete selected pages from a PDF file.",
    category: "pdf",
    icon: "FileText",
    route: "/tools/remove-pdf-pages",
    isFeatured: false,
    isHidden: false,
    sortOrder: 10,
    inputFormats: [".pdf"],
    outputFormats: [".pdf"],
  },
  {
    slug: "add-page-numbers",
    name: "Add Page Numbers",
    description: "Add page numbers to the bottom center of your PDF pages.",
    category: "pdf",
    icon: "FileText",
    route: "/tools/add-page-numbers",
    isFeatured: false,
    isHidden: false,
    sortOrder: 11,
    inputFormats: [".pdf"],
    outputFormats: [".pdf"],
  },

  // Image Category
  {
    slug: "compress-image",
    name: "Compress Image",
    description: "Reduce image file size with adjustable quality settings.",
    category: "image",
    icon: "Image",
    route: "/tools/compress-image",
    isFeatured: true,
    isHidden: false,
    sortOrder: 12,
    inputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputFormats: [".jpg", ".png", ".webp"],
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    description: "Change width and height dimensions of an image.",
    category: "image",
    icon: "Image",
    route: "/tools/resize-image",
    isFeatured: true,
    isHidden: false,
    sortOrder: 13,
    inputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputFormats: [".jpg", ".png", ".webp"],
  },
  {
    slug: "convert-image",
    name: "Convert Image Format",
    description: "Convert between JPG, PNG, WebP, SVG, and other formats.",
    category: "image",
    icon: "Image",
    route: "/tools/convert-image",
    isFeatured: false,
    isHidden: false,
    sortOrder: 14,
    inputFormats: [".jpg", ".jpeg", ".png", ".webp", ".svg"],
    outputFormats: [".jpg", ".png", ".webp"],
  },
  {
    slug: "crop-image",
    name: "Crop Image",
    description: "Crop images to your desired aspect ratios.",
    category: "image",
    icon: "Image",
    route: "/tools/crop-image",
    isFeatured: false,
    isHidden: false,
    sortOrder: 15,
    inputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputFormats: [".jpg", ".png", ".webp"],
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert your images into a PDF document.",
    category: "image",
    icon: "Image",
    route: "/tools/image-to-pdf",
    isFeatured: false,
    isHidden: false,
    sortOrder: 16,
    inputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputFormats: [".pdf"],
  },
  {
    slug: "flip-image",
    name: "Flip Image",
    description: "Flip images vertically or horizontally.",
    category: "image",
    icon: "Image",
    route: "/tools/flip-image",
    isFeatured: false,
    isHidden: false,
    sortOrder: 17,
    inputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputFormats: [".jpg", ".png", ".webp"],
  },
  {
    slug: "rotate-image",
    name: "Rotate Image",
    description: "Rotate images clockwise or counter-clockwise.",
    category: "image",
    icon: "Image",
    route: "/tools/rotate-image",
    isFeatured: false,
    isHidden: false,
    sortOrder: 18,
    inputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputFormats: [".jpg", ".png", ".webp"],
  },
  {
    slug: "watermark-image",
    name: "Watermark Image",
    description: "Add watermark text on top of an image.",
    category: "image",
    icon: "Image",
    route: "/tools/watermark-image",
    isFeatured: false,
    isHidden: false,
    sortOrder: 19,
    inputFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputFormats: [".jpg", ".png", ".webp"],
  },
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    description: "Convert an image into a Base64 data string.",
    category: "image",
    icon: "Image",
    route: "/tools/image-to-base64",
    isFeatured: false,
    isHidden: false,
    sortOrder: 20,
    inputFormats: [".jpg", ".jpeg", ".png", ".webp", ".svg"],
    outputFormats: [".txt"],
  },
  {
    slug: "svg-to-png",
    name: "SVG to PNG",
    description: "Convert vector SVG files into raster PNG images.",
    category: "image",
    icon: "Image",
    route: "/tools/svg-to-png",
    isFeatured: false,
    isHidden: false,
    sortOrder: 21,
    inputFormats: [".svg"],
    outputFormats: [".png"],
  },

  // Text Category
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Analyze character, word, sentence, and paragraph counts.",
    category: "text",
    icon: "AlignLeft",
    route: "/tools/word-counter",
    isFeatured: false,
    isHidden: false,
    sortOrder: 22,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    description: "Generate high-quality custom QR codes for URLs or text.",
    category: "text",
    icon: "AlignLeft",
    route: "/tools/qr-generator",
    isFeatured: true,
    isHidden: false,
    sortOrder: 23,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "base64",
    name: "Base64 Encoder/Decoder",
    description: "Encode or decode strings to and from Base64 format.",
    category: "text",
    icon: "AlignLeft",
    route: "/tools/base64",
    isFeatured: false,
    isHidden: false,
    sortOrder: 24,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Beautify, validate, minify, and format JSON data.",
    category: "text",
    icon: "AlignLeft",
    route: "/tools/json-formatter",
    isFeatured: false,
    isHidden: false,
    sortOrder: 25,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "online-clipboard",
    name: "Online Clipboard",
    description: "Share text clips online across devices temporarily.",
    category: "text",
    icon: "AlignLeft",
    route: "/tools/online-clipboard",
    isFeatured: false,
    isHidden: false,
    sortOrder: 26,
    inputFormats: [],
    outputFormats: [],
  },

  // Calculators
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate exact age from date of birth in years, months, and days.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/age-calculator",
    isFeatured: false,
    isHidden: false,
    sortOrder: 27,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Compute body mass index and find weight category.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/bmi-calculator",
    isFeatured: false,
    isHidden: false,
    sortOrder: 28,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentage increases, decreases, or ratios.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/percentage-calculator",
    isFeatured: false,
    isHidden: false,
    sortOrder: 29,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "cgpa-calculator",
    name: "CGPA Calculator",
    description: "Convert semester grades into CGPA scores.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/cgpa-calculator",
    isFeatured: false,
    isHidden: false,
    sortOrder: 30,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "gpa-calculator",
    name: "GPA Calculator",
    description: "Calculate your semester GPA score based on course credits.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/gpa-calculator",
    isFeatured: false,
    isHidden: false,
    sortOrder: 31,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    description: "Calculate monthly loan EMI repayments and interest schedules.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/emi-calculator",
    isFeatured: false,
    isHidden: false,
    sortOrder: 32,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "sip-calculator",
    name: "SIP Calculator",
    description: "Estimate mutual fund returns from systematic investment plans.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/sip-calculator",
    isFeatured: false,
    isHidden: false,
    sortOrder: 33,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "gst-calculator",
    name: "GST Calculator",
    description: "Calculate GST amounts with net and gross options.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/gst-calculator",
    isFeatured: false,
    isHidden: false,
    sortOrder: 34,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "income-tax-calculator",
    name: "Income Tax Calculator",
    description: "Estimate income tax liabilities based on new/old tax slabs.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/income-tax-calculator",
    isFeatured: false,
    isHidden: false,
    sortOrder: 35,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "currency-converter",
    name: "Currency Converter",
    description: "Convert between global currency exchange rates.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/currency-converter",
    isFeatured: false,
    isHidden: false,
    sortOrder: 36,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "scientific-calculator",
    name: "Scientific Calculator",
    description: "Perform complex scientific operations and equations.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/scientific-calculator",
    isFeatured: false,
    isHidden: false,
    sortOrder: 37,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    description: "Analyze total interest and repayment schedules of a loan.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/loan-calculator",
    isFeatured: false,
    isHidden: false,
    sortOrder: 38,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "discount-calculator",
    name: "Discount Calculator",
    description: "Compute savings and final prices after discounts.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/discount-calculator",
    isFeatured: false,
    isHidden: false,
    sortOrder: 39,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "attendance-calculator",
    name: "Attendance Calculator",
    description: "Calculate needed attendance percentage for classes.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/attendance-calculator",
    isFeatured: false,
    isHidden: false,
    sortOrder: 40,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "date-difference",
    name: "Date Difference",
    description: "Find difference in days, weeks, months, or years between two dates.",
    category: "calculator",
    icon: "Calculator",
    route: "/tools/date-difference",
    isFeatured: false,
    isHidden: false,
    sortOrder: 41,
    inputFormats: [],
    outputFormats: [],
  },

  // Convert Category
  {
    slug: "csv-to-json",
    name: "CSV to JSON",
    description: "Convert CSV files into JSON structure format.",
    category: "convert",
    icon: "RefreshCw",
    route: "/tools/csv-to-json",
    isFeatured: true,
    isHidden: false,
    sortOrder: 42,
    inputFormats: [".csv"],
    outputFormats: [".json"],
  },
  {
    slug: "json-to-csv",
    name: "JSON to CSV",
    description: "Convert JSON arrays into CSV spreadsheets.",
    category: "convert",
    icon: "RefreshCw",
    route: "/tools/json-to-csv",
    isFeatured: false,
    isHidden: false,
    sortOrder: 43,
    inputFormats: [".json"],
    outputFormats: [".csv"],
  },
  {
    slug: "markdown-to-html",
    name: "Markdown to HTML",
    description: "Compile markdown markup syntax into standard HTML code.",
    category: "convert",
    icon: "RefreshCw",
    route: "/tools/markdown-to-html",
    isFeatured: false,
    isHidden: false,
    sortOrder: 44,
    inputFormats: [".md"],
    outputFormats: [".html"],
  },
  {
    slug: "html-to-text",
    name: "HTML to Text",
    description: "Extract clean text out of HTML page codes.",
    category: "convert",
    icon: "RefreshCw",
    route: "/tools/html-to-text",
    isFeatured: false,
    isHidden: false,
    sortOrder: 45,
    inputFormats: [".html"],
    outputFormats: [".txt"],
  },
  {
    slug: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode URLs to safe strings or decode back.",
    category: "convert",
    icon: "RefreshCw",
    route: "/tools/url-encoder",
    isFeatured: false,
    isHidden: false,
    sortOrder: 46,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "color-converter",
    name: "Color Code Converter",
    description: "Convert between HEX, RGB, HSL, and CMYK color spaces.",
    category: "convert",
    icon: "RefreshCw",
    route: "/tools/color-converter",
    isFeatured: false,
    isHidden: false,
    sortOrder: 47,
    inputFormats: [],
    outputFormats: [],
  },
  {
    slug: "number-base",
    name: "Number Base Converter",
    description: "Convert numbers between binary, octal, decimal, and hex bases.",
    category: "convert",
    icon: "RefreshCw",
    route: "/tools/number-base",
    isFeatured: false,
    isHidden: false,
    sortOrder: 48,
    inputFormats: [],
    outputFormats: [],
  },
];

const settings = [
  { key: "site_title", value: "5toolbox - Free Online File Tools" },
  { key: "site_description", value: "Free browser-based file toolkit — merge PDFs, compress images, convert files, generate QR codes and more." },
  { key: "admin_password", value: "admin123" },
  { key: "total_visitors", value: "0" },
  { key: "adsense_enabled", value: "false" },
];

const defaultBlogs = [
  {
    slug: "how-to-compress-pdf",
    title: "How to Compress PDF Files Online Without Losing Quality",
    summary: "Learn the secrets to compressing PDF files safely and locally in your browser without uploading sensitive files to cloud servers.",
    content: "## Why Compress PDF Files?\nPDF documents can easily grow in size, especially when they contain high-resolution scans, images, or graphics. Large PDF files can be difficult to email, upload to portals, or share over messaging apps.\n\n## The Risks of Online PDF Compressors\nMost traditional online compressors require you to upload your files to their external servers. This poses significant privacy and security risks, particularly for personal, medical, or financial documents.\n\n## The 5toolbox Solution\nWith **5toolbox**, we use advanced browser APIs and WebAssembly to compress PDFs directly on your device. Your file never leaves your computer, making it 100% private and extremely fast.\n\n### Steps to Compress a PDF on 5toolbox:\n1. Navigate to the **Compress PDF** tool page.\n2. Drag and drop your PDF file into the upload zone.\n3. Adjust the compression level (Low, Medium, or High) based on your balance preference between size and visual quality.\n4. Click 'Compress' and download your optimized PDF instantly!",
    metaTitle: "Compress PDF Online Without Quality Loss - 5toolbox Guide",
    metaDescription: "Step-by-step guide to compressing PDF files locally in your browser. Fast, 100% secure, and offline capable using 5toolbox.",
    tags: ["pdf", "compression", "privacy", "productivity"],
    category: "PDF Tools",
    authorName: "5toolbox Editor",
    readTime: 4,
  },
  {
    slug: "optimizing-images-core-web-vitals",
    title: "Optimizing Images for Core Web Vitals & Faster Page Load",
    summary: "Image sizes heavily affect your website's performance and Google ranking. Learn how to convert and compress images effectively.",
    content: "## The Importance of Core Web Vitals\nCore Web Vitals are a set of metrics used by Google to measure user experience, including loading performance (LCP), interactivity (FID), and visual stability (CLS). Images are often the primary cause of poor LCP scores.\n\n## Best Formats for Web Images\n* **WebP**: Offers superior lossless and lossy compression compared to PNG and JPEG.\n* **AVIF**: Next-gen compression that results in even smaller sizes, though support is slightly newer.\n\n## How to Optimize Your Images\n1. **Resize Dimensions**: Do not upload a 4000px image if it only renders at 800px width.\n2. **Compress Wisely**: Aim for an index quality level of 80% to shave off 70-80% of file weight with zero noticeable difference.\n3. **Use 5toolbox**: Switch to the **Compress Image** tool, upload your file, select WebP or JPG, and download the compressed copy in seconds.",
    metaTitle: "Optimize Web Images for Google Core Web Vitals - 5toolbox Blog",
    metaDescription: "Learn how image compression and next-gen formats like WebP affect your site's LCP and how to optimize them safely in your browser.",
    tags: ["image", "seo", "web-vitals", "optimization"],
    category: "Image Tools",
    authorName: "SEO Specialist",
    readTime: 5,
  }
];

const defaultArticles = [
  {
    slug: "what-is-browser-based-file-processing",
    title: "What is Browser-Based File Processing and Why is it Safer?",
    summary: "Explore the technology behind WebAssembly and client-side processing that keeps your files 100% private.",
    content: "## What is Client-Side Processing?\nTraditionally, websites that process files (like converting a Word document to PDF) upload your file to their server, process it on their backend CPU, and send the result back to you.\n\n## The Security Loophole\nWhile this works, it means a copy of your document resides on someone else's server, making it vulnerable to hacks, leakage, or logging.\n\n## Enter WebAssembly (Wasm)\nWebAssembly is a technology that allows programming languages like C, C++, and Rust to run directly inside the browser at near-native speeds. It allows 5toolbox to run full compression and conversion algorithms locally inside your browser tab. Your files never leave your device, ensuring maximum security.",
    metaTitle: "Security Guide: What is Browser-Based File Processing? - 5toolbox",
    metaDescription: "A technical guide to client-side file processing, WebAssembly, and why browser-based tools are the future of secure document management.",
    authorName: "Security Team",
    readTime: 3,
  }
];

async function seed() {
  console.log("Seeding database...");
  try {
    // Seed tools
    for (const tool of tools) {
      await db.insert(toolsTable).values(tool).onConflictDoUpdate({
        target: toolsTable.slug,
        set: tool,
      });
    }
    console.log(`Successfully seeded ${tools.length} tools.`);

    // Seed settings
    for (const setting of settings) {
      await db.insert(siteSettingsTable).values(setting).onConflictDoUpdate({
        target: siteSettingsTable.key,
        set: setting,
      });
    }
    console.log(`Successfully seeded ${settings.length} site settings.`);

    // Seed blogs
    for (const blog of defaultBlogs) {
      await db.insert(blogsTable).values(blog).onConflictDoUpdate({
        target: blogsTable.slug,
        set: blog,
      });
    }
    console.log(`Successfully seeded ${defaultBlogs.length} blogs.`);

    // Seed articles
    for (const article of defaultArticles) {
      await db.insert(articlesTable).values(article).onConflictDoUpdate({
        target: articlesTable.slug,
        set: article,
      });
    }
    console.log(`Successfully seeded ${defaultArticles.length} articles.`);

    console.log("Seeding complete!");
  } catch (error) {
    console.error("Failed to seed database:", error);
  }
}

seed().catch(err => {
  console.error("Unhandled seeding error:", err);
});
